app_name: devflow
app_title: About
default_title: "Links and Stuff"
sub_title: "from me"
app_url: http://www.mpet45.co.uk/
rss_url: http://feeds.feedburner.com/Rubyflow
meta_keywords: "blog, news, geeky"
meta_author: "Kevin Evans"
body_class: devflow
ga: UA-54037-4
sidebar: |-
  <h3>What?</h3><p>nothing just yet.</p>